// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_format_pipeline
Rcpp::String cpp_format_pipeline(std::string code, std::string indent_str, std::string wrap, bool expand_if, std::string brace_style, int line_limit, bool function_space, std::string control_braces, bool join_else);
RcppExport SEXP _rformat_cpp_format_pipeline(SEXP codeSEXP, SEXP indent_strSEXP, SEXP wrapSEXP, SEXP expand_ifSEXP, SEXP brace_styleSEXP, SEXP line_limitSEXP, SEXP function_spaceSEXP, SEXP control_bracesSEXP, SEXP join_elseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type code(codeSEXP);
    Rcpp::traits::input_parameter< std::string >::type indent_str(indent_strSEXP);
    Rcpp::traits::input_parameter< std::string >::type wrap(wrapSEXP);
    Rcpp::traits::input_parameter< bool >::type expand_if(expand_ifSEXP);
    Rcpp::traits::input_parameter< std::string >::type brace_style(brace_styleSEXP);
    Rcpp::traits::input_parameter< int >::type line_limit(line_limitSEXP);
    Rcpp::traits::input_parameter< bool >::type function_space(function_spaceSEXP);
    Rcpp::traits::input_parameter< std::string >::type control_braces(control_bracesSEXP);
    Rcpp::traits::input_parameter< bool >::type join_else(join_elseSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_format_pipeline(code, indent_str, wrap, expand_if, brace_style, line_limit, function_space, control_braces, join_else));
    return rcpp_result_gen;
END_RCPP
}
// cpp_format_all
Rcpp::String cpp_format_all(std::string code, std::string indent_str, std::string wrap, bool expand_if, std::string brace_style, int line_limit, bool function_space, std::string control_braces, bool join_else);
RcppExport SEXP _rformat_cpp_format_all(SEXP codeSEXP, SEXP indent_strSEXP, SEXP wrapSEXP, SEXP expand_ifSEXP, SEXP brace_styleSEXP, SEXP line_limitSEXP, SEXP function_spaceSEXP, SEXP control_bracesSEXP, SEXP join_elseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type code(codeSEXP);
    Rcpp::traits::input_parameter< std::string >::type indent_str(indent_strSEXP);
    Rcpp::traits::input_parameter< std::string >::type wrap(wrapSEXP);
    Rcpp::traits::input_parameter< bool >::type expand_if(expand_ifSEXP);
    Rcpp::traits::input_parameter< std::string >::type brace_style(brace_styleSEXP);
    Rcpp::traits::input_parameter< int >::type line_limit(line_limitSEXP);
    Rcpp::traits::input_parameter< bool >::type function_space(function_spaceSEXP);
    Rcpp::traits::input_parameter< std::string >::type control_braces(control_bracesSEXP);
    Rcpp::traits::input_parameter< bool >::type join_else(join_elseSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_format_all(code, indent_str, wrap, expand_if, brace_style, line_limit, function_space, control_braces, join_else));
    return rcpp_result_gen;
END_RCPP
}
// cpp_set_trace
void cpp_set_trace(bool enable);
RcppExport SEXP _rformat_cpp_set_trace(SEXP enableSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< bool >::type enable(enableSEXP);
    cpp_set_trace(enable);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rformat_cpp_format_pipeline", (DL_FUNC) &_rformat_cpp_format_pipeline, 9},
    {"_rformat_cpp_format_all", (DL_FUNC) &_rformat_cpp_format_all, 9},
    {"_rformat_cpp_set_trace", (DL_FUNC) &_rformat_cpp_set_trace, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_rformat(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
