# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_format_pipeline <- function(code, indent_str, wrap, expand_if, brace_style, line_limit, function_space, control_braces) {
    .Call(`_rformat_cpp_format_pipeline`, code, indent_str, wrap, expand_if, brace_style, line_limit, function_space, control_braces)
}

cpp_format_all <- function(code, indent_str, wrap, expand_if, brace_style, line_limit, function_space, control_braces) {
    .Call(`_rformat_cpp_format_all`, code, indent_str, wrap, expand_if, brace_style, line_limit, function_space, control_braces)
}

cpp_set_trace <- function(enable) {
    invisible(.Call(`_rformat_cpp_set_trace`, enable))
}

